import { VaseParams } from '../vaseParams';

/** Generate the OpenSCAD code that invokes the vase() module with the given parameters. */
export function generateScadCode(params: VaseParams): string {
  const boolToStr = (v: boolean): string => (v ? 'true' : 'false');

  return `// Generated by Parametric Vase Designer GUI
// Open this file in OpenSCAD alongside parametric_vase.scad to render.

// Include the parametric vase library
use <parametric_vase.scad>

vase(height=${params.height},
     bottom_sides=${params.bottom_sides},
     mid_sides=${params.mid_sides},
     top_sides=${params.top_sides},
     base_radius=${params.base_radius},
     top_radius=${params.top_radius},
     waist1_pos=${params.waist1_pos},
     waist1_scale=${params.waist1_scale},
     waist2_pos=${params.waist2_pos},
     waist2_scale=${params.waist2_scale},
     twist_degrees=${params.twist_degrees},
     segments=${params.segments},
     pattern_type=${params.pattern_type},
     pattern_amplitude=${params.pattern_amplitude},
     pattern_freq_phi=${params.pattern_freq_phi},
     pattern_freq_z=${params.pattern_freq_z},
     ellipse_ratio=${params.ellipse_ratio},
     rounded_radius=${params.rounded_radius},
     wall_thickness=${params.wall_thickness},
     add_slots=${boolToStr(params.add_slots)},
     slot_count=${params.slot_count},
     slot_radius=${params.slot_radius},
     slot_height=${params.slot_height},
     slot_offset=${params.slot_offset},
     slot_distance_ratio=${params.slot_distance_ratio},
     extra_mid_sides=${params.extra_mid_sides},
     extra_mid_pos=${params.extra_mid_pos},
     extra_waist_scale=${params.extra_waist_scale},
     extra_waist_pos=${params.extra_waist_pos},
     add_bottom_holes=${boolToStr(params.add_bottom_holes)},
     bottom_hole_count=${params.bottom_hole_count},
     bottom_hole_radius=${params.bottom_hole_radius},
     bottom_hole_distance_ratio=${params.bottom_hole_distance_ratio});
`;
}
